# Generated by Django 5.0.1 on 2024-01-11 20:56

import ckeditor.fields
import django.db.models.deletion
import homes.models
import homes.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, verbose_name='Идентификатор')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Позиция в списке')),
                ('cover', models.ImageField(help_text='Только JPEG 16x9', upload_to=homes.models.home_cover_path, validators=[homes.validators.validate_16x9_jpeg], verbose_name='Обложка')),
                ('cost_per_day', models.PositiveIntegerField(verbose_name='Цена за сутки')),
                ('show_on_site', models.BooleanField(default=False, verbose_name='Показывать на сайте')),
                ('short_description', models.TextField(blank=True, default='', verbose_name='Краткое описание')),
                ('long_description', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Полное описание')),
                ('ya_map', models.TextField(blank=True, default='', verbose_name='Код яндекс карт')),
                ('video', models.TextField(blank=True, default='', verbose_name='Код на видео Youtube')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Есть Wi-Fi')),
                ('has_minibar', models.BooleanField(default=False, verbose_name='Есть минибар')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Есть парковка')),
                ('has_hairdryer', models.BooleanField(default=False, verbose_name='Есть фен')),
                ('has_workspace', models.BooleanField(default=False, verbose_name='Есть рабочая зона')),
                ('has_safe', models.BooleanField(default=False, verbose_name='Есть сейф')),
                ('has_washing_machine', models.BooleanField(default=False, verbose_name='Есть стиральная машина')),
                ('has_swimming_pool', models.BooleanField(default=False, verbose_name='Есть бассейн')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
                'db_table': 'homes',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='HomeCarouselImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(verbose_name='Позиция в карусели')),
                ('image', models.ImageField(help_text='Только JPEG 16x9', upload_to=homes.models.carousel_image_path, validators=[homes.validators.validate_16x9_jpeg], verbose_name='Фото')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel', to='homes.home')),
            ],
            options={
                'verbose_name': 'Дополнительная фотография дома',
                'verbose_name_plural': 'Дополнительные фотографии дома (карусель)',
                'db_table': 'home_carousel_images',
                'ordering': ('position',),
                'unique_together': {('home', 'position')},
            },
        ),
    ]
