# Generated by Django 5.0.1 on 2024-01-10 13:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='show_on_site',
            field=models.BooleanField(default=False, verbose_name='Показывать на сайте'),
        ),
        migrations.AlterField(
            model_name='home',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='homecarouselimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
