# Generated by Django 5.0.1 on 2024-01-28 02:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='homecarouselimage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='homecarouselimage',
            name='name',
            field=models.CharField(default='хы', max_length=30, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Название'),
            preserve_default=False,
        ),
    ]
