# Generated by Django 5.0.1 on 2024-01-10 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_home_show_on_site_alter_home_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='has_fan',
            new_name='has_hairdryer',
        ),
    ]
