# Generated by Django 5.0.1 on 2024-01-10 23:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_rename_has_fan_home_has_hairdryer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Полное описание'),
        ),
    ]
