# Generated by Django 5.0.1 on 2024-01-14 00:08

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_ticket_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='Обработано'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Отправлено клиентом'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='end_date',
            field=models.DateField(verbose_name='Конец брони'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='homes.home', verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='start_date',
            field=models.DateField(verbose_name='Начало брони'),
        ),
    ]
