# Generated by Django 5.0.1 on 2024-01-14 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_ticket_processed_alter_ticket_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='processed',
        ),
        migrations.AddField(
            model_name='ticket',
            name='comment',
            field=models.TextField(default='', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='guest_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Количество гостей'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='name',
            field=models.CharField(default='', max_length=30, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Новая'), (2, 'В обработке'), (3, 'Закрыта')], default=1, verbose_name='Статус'),
        ),
    ]
