# Generated by Django 5.0.1 on 2024-01-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_remove_ticket_processed_ticket_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Имя'),
        ),
    ]
