# Generated by Django 5.0.1 on 2024-01-30 20:26

import django.core.validators
import django.db.models.deletion
import homes.models
import homes.validators
import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, verbose_name='Идентификатор')),
                ('address', models.CharField(max_length=200, verbose_name='Адрес')),
                ('position', models.PositiveIntegerField(blank=True, null=True, verbose_name='Позиция в списке')),
                ('cover', models.ImageField(help_text='Только JPEG 16x9', upload_to=homes.models.home_cover_path, validators=[homes.validators.validate_16x9_jpeg], verbose_name='Обложка')),
                ('cost_per_day', models.PositiveIntegerField(verbose_name='Цена за сутки')),
                ('show_on_site', models.BooleanField(default=False, verbose_name='Показывать на сайте')),
                ('short_description', models.TextField(blank=True, default='', verbose_name='Краткое описание')),
                ('ya_map', models.TextField(blank=True, default='', verbose_name='Код яндекс карт')),
                ('video', models.TextField(blank=True, default='', verbose_name='Ссылка видео Youtube')),
                ('conv_wifi', models.BooleanField(default=False, verbose_name='Wi-Fi')),
                ('conv_minibar', models.BooleanField(default=False, verbose_name='Минибар')),
                ('conv_parking', models.BooleanField(default=False, verbose_name='Парковка')),
                ('conv_hairdryer', models.BooleanField(default=False, verbose_name='Фен')),
                ('conv_workspace', models.BooleanField(default=False, verbose_name='Рабочая зона')),
                ('conv_safe', models.BooleanField(default=False, verbose_name='Сейф')),
                ('conv_washing_machine', models.BooleanField(default=False, verbose_name='Стиральная машина')),
                ('conv_swimming_pool', models.BooleanField(default=False, verbose_name='Бассейн')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
                'db_table': 'homes',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='HomeCarouselImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(verbose_name='Позиция в карусели')),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Название')),
                ('image', models.ImageField(help_text='Только JPEG 16x9', upload_to=homes.models.carousel_image_path, validators=[homes.validators.validate_16x9_jpeg], verbose_name='Фото')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel', to='homes.home')),
            ],
            options={
                'verbose_name': 'Дополнительная фотография дома',
                'verbose_name_plural': 'Дополнительные фотографии дома (карусель)',
                'db_table': 'home_carousel_images',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=30, verbose_name='Имя')),
                ('start_date', models.DateField(verbose_name='Начало брони')),
                ('end_date', models.DateField(verbose_name='Конец брони')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Телефон')),
                ('guest_count', models.PositiveSmallIntegerField(verbose_name='Количество гостей')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено клиентом')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Новая'), (2, 'В обработке'), (3, 'Закрыта')], default=1, verbose_name='Статус')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='homes.home', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'tickets',
            },
        ),
    ]
