# Generated by Django 5.0.1 on 2024-02-15 01:01

import homes.model_fields
import homes.models
import homes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='area',
            field=models.CharField(blank=True, default='', max_length=25, verbose_name='Микрорайон'),
        ),
        migrations.AlterField(
            model_name='home',
            name='cover',
            field=homes.model_fields.ProgressiveJpegField(help_text='Только JPEG 16x9', upload_to=homes.models.home_cover_path, validators=[homes.validators.validate_16x9_jpeg], verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='homecarouselimage',
            name='image',
            field=homes.model_fields.ProgressiveJpegField(help_text='Только JPEG 16x9', upload_to=homes.models.carousel_image_path, validators=[homes.validators.validate_16x9_jpeg], verbose_name='Фото'),
        ),
    ]
